### ISSUE TITLE
Conda install Diffsinger Error Data

### ISSUE THREAD

**Issue by usasho** [openvpi/DiffSinger#124]
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "scripts/train.py", line 31, in <module>
    run_task()
  File "scripts/train.py", line 27, in run_task
    task_cls.start()
  File "E:\scss\diff\basics\base_task.py", line 442, in start
    trainer.fit(task, ckpt_path=get_latest_checkpoint_path(work_dir))
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 973, in _run
    results = self._run_stage()
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1014, in _run_stage
    self._run_sanity_check()
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1043, in _run_sanity_check
    val_loop.run()
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\loops\utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 108, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\loops\fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 284, in __next__
    out = next(self._iterator)
  File "E:\hange\envs\scss\lib\site-packages\lightning\pytorch\utilities\combined_loader.py", line 123, in __next__
    out = next(self.iterators[0])
  File "E:\hange\envs\scss\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "E:\hange\envs\scss\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "E:\hange\envs\scss\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "E:\hange\envs\scss\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\hange\envs\scss\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\hange\envs\scss\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "E:\scss\diff\training\variance_task.py", line 48, in collater
    batch['uv'] = utils.collate_nd([s['uv'] for s in samples], True)
  File "E:\scss\diff\training\variance_task.py", line 48, in <listcomp>
    batch['uv'] = utils.collate_nd([s['uv'] for s in samples], True)
KeyError: 'uv'

**Comment by yqzhishen** [comment]
If you are training a pitch predictor, please re-binarize your dataset because the RPA introduced in #123 needs the new attribute `uv` for computing.

**Comment by usasho** [comment]
Thanks
