### ISSUE TITLE
onnx模型导出错误

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#136]
我按照文档中的内容，安装了所有依赖但在导出模型的过程中依然报错

pytorch版本为文档中的版本

模型为variance模型
```
E:\DiffSinger\modules\commons\espnet_positional_embedding.py:27: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.pe.size(1) >= x.size(1):
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py:687: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py:687: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
Exporting DurationPredictor...
D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Traceback (most recent call last):
  File "scripts/export.py", line 231, in <module>
    main()
  File "D:\miniconda3\envs\onnx\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\miniconda3\envs\onnx\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\miniconda3\envs\onnx\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\miniconda3\envs\onnx\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\miniconda3\envs\onnx\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "scripts/export.py", line 188, in variance
    exporter.export(out)
  File "E:\DiffSinger\deployment\exporters\variance_exporter.py", line 94, in export
    self.export_model(path, model_name)
  File "E:\DiffSinger\deployment\exporters\variance_exporter.py", line 98, in export_model
    self._torch_export_model()
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\DiffSinger\deployment\exporters\variance_exporter.py", line 261, in _torch_export_model
    torch.onnx.export(
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\onnx\utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\jit\_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\miniconda3\envs\onnx\lib\site-packages\torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "E:\DiffSinger\deployment\modules\toplevel.py", line 177, in forward_pitch_preprocess
    expr = (expr * retake)[:, :, None]  # [B, T, 1]
TypeError: only integer tensors of a single element can be converted to an index
```

**Comment by SuSWhW** [comment]
并且由openSVIP转换出来的ds文件也无法推理

**Comment by yqzhishen** [comment]
更新代码
