### ISSUE TITLE
Error preventing preprocessing

### ISSUE THREAD

**Issue by agentasteriski** [openvpi/DiffSinger#160]
Lately, this error has been completely preventing me from processing my audio.
```
binarizing acoustic...
python scripts/binarize.py --config configs/acoustic.yaml
| load phoneme set: ['AP', 'I', 'N', 'O', 'SP', 'U', 'a', 'aa', 'ae', 'ah', 'ao', 'aw', 'ax', 'ay', 'b', 'by', 'ch', 'cl', 'd', 'dh', 'dr', 'dx', 'e', 'eh', 'er', 'ey', 'f', 'g', 'gy', 'h', 'hh', 'hy', 'i', 'ih', 'iy', 'j', 'jh', 'k', 'ky', 'l', 'm', 'my', 'n', 'ng', 'ny', 'o', 'ow', 'oy', 'p', 'py', 'q', 'r', 'rx', 'ry', 's', 'sh', 't', 'th', 'tr', 'ts', 'u', 'uh', 'uw', 'v', 'vf', 'vtrash', 'w', 'y', 'z', 'zh']
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:15<00:00,  1.17it/s]
  0%|                                                                                          | 0/513 [00:00<?, ?it/s]C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
  0%|                                                                                          | 0/513 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'F:\\DiffSinger\\ds_training_gui\\DiffSinger\\data\\AC3\\01CORE\\wavs\\.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\DiffSinger\ds_training_gui\DiffSinger\scripts\binarize.py", line 25, in <module>
    binarize()
  File "F:\DiffSinger\ds_training_gui\DiffSinger\scripts\binarize.py", line 21, in binarize
    binarizer_cls().process()
  File "F:\DiffSinger\ds_training_gui\DiffSinger\basics\base_binarizer.py", line 191, in process
    self.process_dataset(
  File "F:\DiffSinger\ds_training_gui\DiffSinger\basics\base_binarizer.py", line 307, in process_dataset
    item = self.process_item(*a)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\DiffSinger\ds_training_gui\DiffSinger\preprocessing\acoustic_binarizer.py", line 84, in process_item
    wav, mel = VOCODERS[hparams['vocoder']].wav2spec(meta_data['wav_fn'])
  File "F:\DiffSinger\ds_training_gui\DiffSinger\modules\vocoders\nsf_hifigan.py", line 114, in wav2spec
    wav_torch, _ = load_wav_to_torch(inp_path, target_sr=stft.target_sr)
  File "F:\DiffSinger\ds_training_gui\DiffSinger\modules\nsf_hifigan\nvSTFT.py", line 13, in load_wav_to_torch
    data, sr = librosa.load(full_path, sr=target_sr, mono=True)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "C:\Users\AAAAA\AppData\Local\Programs\Python\Python39\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\DiffSinger\\ds_training_gui\\DiffSinger\\data\\AC3\\01CORE\\wavs\\.wav'
```

Steps I have already taken, with no success:

- Examined file names for errors
- Rewrote config file
- Replaced script files with clean, up to date version
- Normalized audio to ensure identical file formats

The model is multi-speaker with 6 subfolders. There are definitely .wavs in 01core/wavs.

**Comment by agentasteriski** [comment]
cause of error: while manually assembling transcriptions.csv, a stray column header was left in note_dur causing some rows to be one off, and one file would have no valid note_dur. attempting to binarize variance instead of acoustic produced a more helpful error.
