### ISSUE TITLE
mfa无法使用

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#37]
```bash
BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Q78KGa\miniconda3\envs\diff\Scripts\mfa-script.py", line 6, in <module>
    from montreal_forced_aligner.command_line.mfa import main
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\__init__.py", line 4, in <module>
    import montreal_forced_aligner.acoustic_modeling as acoustic_modeling
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\acoustic_modeling\__init__.py", line 7, in <module>
    from montreal_forced_aligner.acoustic_modeling.base import AcousticModelTrainingMixin  # noqa
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\acoustic_modeling\base.py", line 20, in <module>
    from montreal_forced_aligner.alignment import AlignMixin
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\alignment\__init__.py", line 6, in <module>
    from montreal_forced_aligner.alignment.adapting import AdaptingAligner
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\alignment\adapting.py", line 15, in <module>
    from montreal_forced_aligner.alignment.multiprocessing import AccStatsArguments, AccStatsFunction
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\alignment\multiprocessing.py", line 28, in <module>
    from montreal_forced_aligner.db import (
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\montreal_forced_aligner\db.py", line 327, in <module>
    class Word(MfaSqlBase):
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_api.py", line 194, in __init__
    _as_declarative(reg, cls, dict_)
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_base.py", line 246, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_base.py", line 327, in setup_mapping
    return _ClassScanMapperConfig(
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_base.py", line 558, in __init__
    self._scan_attributes()
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1000, in _scan_attributes
    collected_annotation = self._collect_annotation(
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1142, in _collect_annotation
    extracted = _extract_mapped_subtype(
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\site-packages\sqlalchemy\orm\util.py", line 2306, in _extract_mapped_subtype
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Type annotation for "Word.dictionary" can't be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legacy annotations which don't use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class. (Background on this error at: https://sqlalche.me/e/20/zlpr)
```

所有的环境安装均严格按照文档，在第一次出现该问题时尝试过删除环境重装，但是仍然有这个问题

**Comment by SuSWhW** [comment]
我真傻，真的，我单知道环境配置是个玄学东西， 没想到真的那么玄学

**Comment by yqzhishen** [comment]
@AlexandaJerry 这个问题你知道怎么解决吗？

**Comment by AlexandaJerry** [comment]
> 

不知道 第一次见到这个

**Comment by yqzhishen** [comment]
亿眼顶针鉴定为MFA没锁次级依赖版本，解决方案：
```bash
pip install sqlalchemy==1.4.46
```
