### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#40]
```bash
Traceback (most recent call last):
  File "data_gen/binarize.py", line 6, in <module>
    from utils.hparams import set_hparams, hparams
ModuleNotFoundError: No module named 'utils.hparams'
```

**Comment by SuSWhW** [comment]
卡在预处理那一步了

**Comment by yqzhishen** [comment]
你可能忘了设置 PYTHONPATH 环境变量，仔细看看吧

**Comment by SuSWhW** [comment]
有没有一种可能我设置了（

**Comment by SuSWhW** [comment]
![image](https://user-images.githubusercontent.com/120356642/215313859-2e132173-02be-49b1-8758-99c0af9040b2.png)

**Comment by SuSWhW** [comment]
没事了，我看错终端了

**Comment by SuSWhW** [comment]
好吧现在又出问题了
```bash
| Hparams chains:  ['configs/basics/base.yaml', 'configs/basics/fs2.yaml', 'configs/acoustic/nomidi.yaml', 'data/Haiyi_v1small/config.yaml']
| Hparams:
K_step: 1000, accumulate_grad_batches: 1, audio_num_mel_bins: 128, audio_sample_rate: 44100, base_config: ['configs/acoustic/nomidi.yaml'],
binarization_args: {'shuffle': False, 'with_txt': True, 'with_wav': False, 'with_align': True, 'with_spk_embed': False, 'with_f0': True, 'with_f0cwt': True}, binarizer_cls: data_gen.opencpop.OpencpopBinarizer, binary_data_dir: data/Haiyi_v1small/binary, check_val_every_n_epoch: 10, clip_grad_norm: 1,
content_cond_steps: [], cwt_add_f0_loss: False, cwt_hidden_size: 128, cwt_layers: 2, cwt_loss: l1,
cwt_std_scale: 0.8, datasets: ['opencpop'], debug: False, dec_ffn_kernel_size: 9, dec_layers: 4,
decay_steps: 50000, decoder_type: fft, dict_dir: , diff_decoder_type: wavenet, diff_loss_type: l2,
dilation_cycle_length: 4, dropout: 0.1, ds_workers: 4, dur_enc_hidden_stride_kernel: ['0,2,3', '0,2,3', '0,1,3'], dur_loss: mse,
dur_predictor_kernel: 3, dur_predictor_layers: 2, enc_ffn_kernel_size: 9, enc_layers: 4, encoder_K: 8,
encoder_type: fft, endless_ds: True, f0_embed_type: discrete, ffn_act: gelu, ffn_padding: SAME,
fft_size: 2048, fmax: 16000, fmin: 40, g2p_dictionary: dictionaries/opencpop-strict.txt, gaussian_start: True,
gen_dir_name: , gen_tgt_spk_id: -1, hidden_size: 256, hop_size: 512, infer: False,
keep_bins: 128, lambda_commit: 0.25, lambda_energy: 0.0, lambda_f0: 0.0, lambda_ph_dur: 0.0,
lambda_sent_dur: 0.0, lambda_uv: 0.0, lambda_word_dur: 0.0, load_ckpt: , log_interval: 100,
loud_norm: False, lr: 0.0004, max_beta: 0.02, max_epochs: 1000, max_eval_sentences: 1,
max_eval_tokens: 60000, max_frames: 8000, max_input_tokens: 1550, max_sentences: 48, max_tokens: 80000,
max_updates: 320000, mel_loss: ssim:0.5|l1:0.5, mel_vmax: 1.5, mel_vmin: -6.0, min_level_db: -120,
norm_type: gn, num_ckpt_keep: 5, num_heads: 2, num_sanity_val_steps: 1, num_spk: 1,
num_test_samples: 0, num_valid_plots: 10, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.98, original_g2p_dictionary: dictionaries/opencpop-strict.txt,
out_wav_norm: False, permanent_ckpt_interval: 20000, permanent_ckpt_start: 120000, pitch_ar: False, pitch_enc_hidden_stride_kernel: ['0,2,5', '0,2,5', '0,2,5'],
pitch_extractor: parselmouth, pitch_loss: l1, pitch_norm: log, pitch_type: frame, pndm_speedup: 10,
pre_align_args: {'use_tone': True, 'forced_align': 'mfa', 'use_sox': False, 'txt_processor': 'en', 'allow_no_txt': False, 'denoise': False}, pre_align_cls: , predictor_dropout: 0.5, predictor_grad: 0.0, predictor_hidden: -1,
predictor_kernel: 5, predictor_layers: 5, prenet_dropout: 0.5, prenet_hidden_size: 256, pretrain_fs_ckpt: ,
processed_data_dir: , profile_infer: False, raw_data_dir: ['data/Haiyi_v1small/raw'], ref_norm_layer: bn, rel_pos: True,

reset_phone_dict: True, residual_channels: 384, residual_layers: 20, save_best: False, save_ckpt: True,
save_codes: ['configs', 'modules', 'src', 'utils'], save_f0: True, save_gt: False, schedule_type: linear, seed: 1234,
sort_by_len: True, speakers: ['Haiyi'], spec_max: [0], spec_min: [-5], spk_cond_steps: [],
stop_token_weight: 5.0, task_cls: src.naive_task.NaiveTask, test_ids: [], test_input_dir: , test_num: 0,
test_prefixes: ['1_vocal_2', '1_vocal_6', 'ganyin1_Track_2_10', 'ganyin1_Track_2_13', 'ganyin1_Track_2_15', 'ganyin1_Track_2_17', 'ganyin1_Track_2_20', 'ganyin1_Track_2_23', 'ganyin1_Track_2_3', 'srgswx_MixDown_3'], test_set_name: test, timesteps: 1000, train_set_name: train, use_denoise: False,
use_energy_embed: False, use_gt_dur: False, use_gt_f0: False, use_midi: False, use_nsf: True,
use_pitch_embed: True, use_pos_embed: True, use_spk_embed: False, use_spk_id: False, use_split_spk_id: False,
use_uv: False, use_var_enc: False, val_check_interval: 2000, valid_num: 0, valid_set_name: valid,
validate: False, vocoder: NsfHifiGAN, vocoder_ckpt: checkpoints/nsf_hifigan/model, warmup_updates: 2000, wav2spec_eps: 1e-6,
weight_decay: 0, win_size: 2048, work_dir: ,
Traceback (most recent call last):
  File "data_gen/binarize.py", line 20, in <module>
    binarize()
  File "data_gen/binarize.py", line 13, in binarize
    binarizer_cls = getattr(importlib.import_module(pkg), cls_name)
  File "C:\Users\Q78KGa\miniconda3\envs\diff\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Github\DiffSinger-refactor\data_gen\opencpop.py", line 20, in <module>
    from data_gen.midisinging import MidiSingingBinarizer
  File "D:\Github\DiffSinger-refactor\data_gen\midisinging.py", line 4, in <module>
    from data_gen.singing import SingingBinarizer, SINGING_ITEM_ATTRIBUTES
  File "D:\Github\DiffSinger-refactor\data_gen\singing.py", line 7, in <module>
    from basics.base_binarizer import BaseBinarizer, BASE_ITEM_ATTRIBUTES
  File "D:\Github\DiffSinger-refactor\basics\base_binarizer.py", line 11, in <module>
    from data_gen.data_gen_utils import get_mel2ph, get_pitch_parselmouth, build_phone_encoder
  File "D:\Github\DiffSinger-refactor\data_gen\data_gen_utils.py", line 8, in <module>
    from skimage.transform import resize
ModuleNotFoundError: No module named 'skimage'
```

**Comment by SuSWhW** [comment]
我运行了
$env:PYTHONPATH="."
$env:CUDA_VISIBLE_DEVICES=0
然后到下面就这样了

**Comment by SuSWhW** [comment]
我用的是powershell
