### ISSUE TITLE
RuntimeError: DataLoader worker

### ISSUE THREAD

**Issue by SuSWhW** [openvpi/DiffSinger#42]
raceback (most recent call last):                                                    | 2/10 [00:10<00:39,  4.93s/batch]
  File "D:\Miniconda3\envs\diff\lib\site-packages\torch\utils\data\dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\Miniconda3\envs\diff\lib\multiprocessing\queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run_task()
  File "run.py", line 11, in run_task
    task_cls.start()
  File "D:\Github\DiffSinger\basics\base_task.py", line 242, in start
    trainer.fit(task)
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 497, in fit
    self.run_pretrain_routine(model)
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 590, in run_pretrain_routine
    self.train()
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 1365, in train
    self.run_training_epoch()
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 1413, in run_training_epoch
    self.run_evaluation(test=self.testing)
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 1253, in run_evaluation
    eval_results = self.evaluate(self.model,
  File "D:\Github\DiffSinger\utils\pl_utils.py", line 1181, in evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "D:\Miniconda3\envs\diff\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Miniconda3\envs\diff\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "D:\Miniconda3\envs\diff\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "D:\Miniconda3\envs\diff\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 21996) exited unexpectedly

**Comment by SuSWhW** [comment]
这个是在保存检查点的时候抛出的，应该是包的问题

**Comment by SuSWhW** [comment]
这个报错的抛出是因为val_check_interval这个数值，我目前是只保存永久模型，不存检查点
